@startuml

title SSD UC-006 Voorkeuren importeren - Hoofdsucces-scenario

actor "Talentcoördinator" as TalentCoordinator
participant ":Systeem" as Systeem

TalentCoordinator -> Systeem : startVoorkeurImport(talentenPeriode)


Systeem -->> TalentCoordinator : vraagExcelBestand()

TalentCoordinator -> Systeem : importeerVoorkeuren(talentenPeriode, excelBestand)

Systeem -->> TalentCoordinator : toonImportResultaat(importGelukt)

@enduml