package be.kdg.talenten.view.export;

import be.kdg.talenten.domain.*;import be.kdg.talenten.service.beheer.*;import be.kdg.talenten.service.verdeling.VerdelingExcelService;import be.kdg.talenten.view.SceneManager;import be.kdg.talenten.view.main.MainView;import be.kdg.talenten.view.theme.ThemeManager;import javafx.collections.FXCollections;import javafx.concurrent.Task;import javafx.scene.Scene;import javafx.scene.control.*;import javafx.stage.FileChooser;import javafx.util.StringConverter;import java.io.File;import java.nio.file.Path;import java.time.LocalDate;import java.util.*;
public class ExportPresenter {
 private final ExportView view;private final MainView main;private final SceneManager scenes;private final ThemeManager themes;private final Scene scene;private final SchooljaarService jaren;private final TalentenPeriodeService periodes;private final VerdelingExcelService service;
 public ExportPresenter(ExportView v,MainView m,SceneManager s,ThemeManager t,Scene sc,SchooljaarService j,TalentenPeriodeService p,VerdelingExcelService x){if(v==null||m==null||s==null||t==null||sc==null||j==null||p==null||x==null)throw new IllegalArgumentException("ExportPresenter kreeg een null-afhankelijkheid");view=v;main=m;scenes=s;themes=t;scene=sc;jaren=j;periodes=p;service=x;configureer();laadJaren();}
 private void configureer(){view.updateThemeIcon(themes.isDark());view.getTerugButton().setOnAction(e->scenes.toon(main));view.getThemeButton().setOnAction(e->toggle());view.getType().setItems(FXCollections.observableArrayList("Per klas","Per ingericht talent"));view.getType().setValue("Per klas");view.getDoelgroep().setConverter(new StringConverter<>(){public String toString(Doelgroep d){return d==null?"":d==Doelgroep.OBSERVATIE_OPLEIDINGSFASE_EERSTEGRAAD_AB?"Observatie / opleidingsfase / 1e graad A-B":"Kwalificatiefase / 2e graad A-B";}public Doelgroep fromString(String s){return null;}});view.getDoelgroep().setItems(FXCollections.observableArrayList(Doelgroep.values()));view.getDoelgroep().setValue(Doelgroep.OBSERVATIE_OPLEIDINGSFASE_EERSTEGRAAD_AB);view.getSchooljaar().valueProperty().addListener((o,a,n)->laadPeriodes(n));view.getExportButton().setOnAction(e->exporteer());}
 private void laadJaren(){try{List<Schooljaar> l=jaren.zoekAlleSchooljaren().stream().sorted(Comparator.comparing(Schooljaar::getStartDatum).reversed()).toList();view.getSchooljaar().setItems(FXCollections.observableArrayList(l));view.getSchooljaar().setValue(jaren.zoekActiefSchooljaar().orElse(l.isEmpty()?null:l.getFirst()));}catch(RuntimeException e){view.toonStatus(msg(e,"De schooljaren konden niet geladen worden."),true);}}
 private void laadPeriodes(Schooljaar j){if(j==null){view.getPeriode().getItems().clear();return;}try{List<TalentenPeriode> l=periodes.geefPeriodesVoorSchooljaar(j).stream().sorted(Comparator.comparing(TalentenPeriode::getStartDatum)).toList();view.getPeriode().setItems(FXCollections.observableArrayList(l));view.getPeriode().setValue(passende(l,LocalDate.now()));}catch(RuntimeException e){view.toonStatus(msg(e,"De periodes konden niet geladen worden."),true);}}
 static TalentenPeriode passende(List<TalentenPeriode> l,LocalDate d){return l.stream().filter(p->!d.isBefore(p.getStartDatum())&&!d.isAfter(p.getEindDatum())).findFirst().orElseGet(()->l.stream().filter(p->p.getStartDatum().isAfter(d)).findFirst().orElse(l.isEmpty()?null:l.getLast()));}
 private void exporteer(){TalentenPeriode p=view.getPeriode().getValue();Doelgroep d=view.getDoelgroep().getValue();String type=view.getType().getValue();if(p==null||d==null||type==null){view.toonStatus("Selecteer eerst alle exportopties.",true);return;}FileChooser c=new FileChooser();c.setTitle("Excel-lijst opslaan");c.setInitialFileName((type.equals("Per klas")?"Verdeling_per_klas_":"Verdeling_per_talent_")+p.getNaam()+".xlsx");c.getExtensionFilters().add(new FileChooser.ExtensionFilter("Excelbestand (*.xlsx)","*.xlsx"));File f=c.showSaveDialog(scene.getWindow());if(f==null)return;view.getExportButton().setDisable(true);Task<Void> task=new Task<>(){protected Void call(){if(type.equals("Per klas"))service.exporteerPerKlas(p,d,Path.of(f.toURI()));else service.exporteerPerIngerichtTalent(p,d,Path.of(f.toURI()));return null;}};task.setOnSucceeded(e->{view.getExportButton().setDisable(false);view.toonStatus("De Excel-lijst is opgeslagen als "+f.getName()+".",false);});task.setOnFailed(e->{view.getExportButton().setDisable(false);view.toonStatus(msg(task.getException(),"De Excel-lijst kon niet aangemaakt worden."),true);});Thread th=new Thread(task,"verdeling-exporteren");th.setDaemon(true);th.start();}
 private String msg(Throwable e,String s){return e!=null&&e.getMessage()!=null&&!e.getMessage().isBlank()?e.getMessage():s;}private void toggle(){themes.toggle(scene);boolean d=themes.isDark();view.updateThemeIcon(d);main.updateThemeIcon(d);}
}
